base_url = "https://zokosting.github.io/rssyt"
root     = "podcasts"
backlog  = 5

[[podcasts]]
url           = "https://www.youtube.com/@rubensancheztw"
title         = "Amigo y vecino"
folder        = "rubensancheztw"
backlog       = 3
backlog_order = "asc"
pubdate       = "download"
